name: github pages

# only build on push to master
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    # use a premade container with some R packages and needed dependencies
    container:
      image: gdamjan/tidy-tuesday-kika:latest
    #  image: docker.pkg.github.com/${{ github.repository_owner }}/tidytuesdayatkika/tidy-tuesday-kika:latest

    steps:
    - uses: actions/checkout@v2

    # most dependencies should be already in the above image, but just in case
    - name: install deps
      run: make deps

    - name: compile all Rmd to htmls
      run: make

    - name: prepare for distribution
      run: |
          make DESTDIR=./public dist
          cp index.html ./public/

    - name: deploy to gh-pages
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: gh-pages
        build_dir: public
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
